-- Schema for tables used by /web/hh (generated 2026-08-26, structure only)

CREATE TABLE `hh_index` (
  `id` int NOT NULL AUTO_INCREMENT,
  `url` varchar(255) DEFAULT NULL,
  `plain_text` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `keywords` varchar(255) DEFAULT NULL,
  `ngt_text` text,
  `zelfopname` varchar(255) DEFAULT NULL,
  `labels` varchar(255) DEFAULT NULL,
  `priority` int DEFAULT NULL,
  `status` varchar(255) DEFAULT NULL,
  `ngt_text2` text,
  `ngt_text3` text,
  `ngt_text4` text,
  `naam` varchar(255) DEFAULT NULL,
  `status_video` varchar(50) DEFAULT '',
  `status_glos` varchar(50) DEFAULT '',
  `status_nederlands` varchar(50) DEFAULT '',
  `status_gvg` varchar(50) DEFAULT '',
  `comments` text,
  `video_count` int DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `url` (`url`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `hh_sentences` (
  `sentence` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `sentence_id` int DEFAULT NULL,
  `id` int NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  KEY `sentence_id` (`sentence_id`),
  KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `hh_words` (
  `word` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `word_id` int DEFAULT NULL,
  `id` int NOT NULL AUTO_INCREMENT,
  `lemma` varchar(255) DEFAULT NULL,
  `origin` varchar(255) DEFAULT NULL,
  `video_id` varchar(255) DEFAULT NULL,
  `video` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `word_id` (`word_id`),
  KEY `ix_hh_words_search` (`id`,`word`,`lemma`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `hh_lemma` (
  `id` int NOT NULL AUTO_INCREMENT,
  `lemma` varchar(255) DEFAULT NULL,
  `video` varchar(255) DEFAULT NULL,
  `origin` varchar(255) DEFAULT NULL,
  `video_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- hh_unique_words: not present in database

CREATE TABLE `hh_index_glos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `hh_index_id` varchar(255) NOT NULL,
  `glos` varchar(255) NOT NULL,
  `text` text NOT NULL,
  KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `hh_segments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `base_filename` varchar(255) NOT NULL COMMENT 'e.g. M20250610_9217',
  `segment_number` int NOT NULL,
  `filename` varchar(255) NOT NULL COMMENT 'e.g. M20250610_9217_3.mp4',
  `location` enum('raw','post','both') NOT NULL DEFAULT 'raw',
  `file_size_raw` bigint DEFAULT NULL,
  `file_size_post` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_base_segment` (`base_filename`,`segment_number`),
  KEY `idx_base_filename` (`base_filename`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `matched_transcriptions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `l_file` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `m_file` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `r_file` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `l_transcription` text CHARACTER SET latin1,
  `m_transcription` text CHARACTER SET latin1,
  `r_transcription` text CHARACTER SET latin1,
  `definitive_outcome` text CHARACTER SET latin1,
  `added` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `a_file` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `b_file` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `a_transcription` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `b_transcription` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `videoCategory` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `videoLabel` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `zOg` varchar(255) CHARACTER SET latin1 NOT NULL,
  `videoTop` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `post_processed` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `signbank_upload` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `time` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `date` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `format` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `tyd_converted` int DEFAULT NULL,
  `rendered` int DEFAULT NULL,
  `converted` int DEFAULT NULL,
  `render_date` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `convert_date` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `thumbnail` int DEFAULT NULL,
  `thumbnail_date` varchar(255) CHARACTER SET latin1 DEFAULT NULL,
  `tyd_rendered` int DEFAULT NULL,
  `tyd_thumbnail` int DEFAULT NULL,
  `app_ready` int DEFAULT '0',
  `has_mocap` int DEFAULT NULL,
  `has_sam` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_m_file` (`m_file`),
  KEY `idx_mocap_filter` (`zOg`,`added`,`has_mocap`,`m_transcription`(20)),
  KEY `idx_m_file_zog` (`m_file`,`zOg`),
  KEY `idx_mt_transcription` (`m_transcription`(13),`zOg`,`added`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `form_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  `signbank` varchar(255) DEFAULT NULL,
  `wie` varchar(255) DEFAULT NULL,
  `actie` text,
  `entry` varchar(255) DEFAULT NULL,
  `gbc` varchar(255) DEFAULT NULL,
  `glos` varchar(255) DEFAULT NULL,
  `wanneer` varchar(255) DEFAULT NULL,
  `wie_snel_opname` varchar(255) DEFAULT NULL,
  `control_nodig` varchar(255) DEFAULT NULL,
  `fonologie_fase1` varchar(255) DEFAULT NULL,
  `fonologie_fase2` varchar(255) DEFAULT NULL,
  `senses` text,
  `linkSignbank` varchar(255) DEFAULT NULL,
  `logboek` longtext,
  `woord` varchar(255) DEFAULT NULL,
  `videoLeft` text,
  `videoCenter` text,
  `videoRight` text,
  `studioOpnameStatus` varchar(255) DEFAULT NULL,
  `studioOpnameWie` varchar(255) DEFAULT NULL,
  `signbank_status` varchar(255) DEFAULT NULL,
  `glosZichtbaar` varchar(255) NOT NULL DEFAULT '0',
  `zelfopname` text,
  `thema` varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci DEFAULT NULL,
  `signbank_opname` varchar(255) DEFAULT NULL,
  `glos_engels` varchar(255) DEFAULT NULL,
  `glosVeranderen` varchar(255) DEFAULT NULL,
  `OpnameThreeD` varchar(255) DEFAULT NULL,
  `unreal_take` text,
  `glosStatus` text,
  `handvorm` text,
  `Handeness` varchar(255) DEFAULT NULL,
  `strongHand` varchar(255) DEFAULT NULL,
  `weakHand` varchar(255) DEFAULT NULL,
  `handLocation` varchar(255) DEFAULT NULL,
  `captureStartTime` text,
  `videoTop` text,
  `synced` varchar(255) DEFAULT NULL,
  `HandshapeChange` varchar(255) DEFAULT NULL,
  `RelationArticulators` varchar(255) DEFAULT NULL,
  `relOrientationMove` varchar(255) DEFAULT NULL,
  `relOrientationLoc` varchar(255) DEFAULT NULL,
  `orientationChange` varchar(255) DEFAULT NULL,
  `ContactType` varchar(255) DEFAULT NULL,
  `MovementShape` varchar(255) DEFAULT NULL,
  `MovementDirection` varchar(255) DEFAULT NULL,
  `RepeatedMovement` varchar(255) DEFAULT NULL,
  `AlternatingMovement` varchar(255) DEFAULT NULL,
  `madeByWie` varchar(255) DEFAULT NULL,
  `relativeOrienationMovement` varchar(255) DEFAULT NULL,
  `relativeOrienationLocation` varchar(255) DEFAULT NULL,
  `virtualObjectt` varchar(255) DEFAULT NULL,
  `phonologyOther` varchar(255) DEFAULT NULL,
  `mouthGesture` varchar(255) DEFAULT NULL,
  `mouthing` varchar(255) DEFAULT NULL,
  `phoneticVariation` varchar(255) DEFAULT NULL,
  `processed` varchar(255) DEFAULT NULL,
  `sensesEngels` text,
  `process_zelfopname` varchar(255) DEFAULT NULL,
  `morfologie` varchar(255) DEFAULT NULL,
  `videoA` varchar(255) DEFAULT NULL,
  `videoB` varchar(255) DEFAULT NULL,
  `origin` varchar(255) DEFAULT NULL,
  `extern` varchar(255) DEFAULT NULL,
  `labels` varchar(255) DEFAULT NULL,
  `werkwoord` varchar(255) DEFAULT NULL,
  `tyd_app_ready` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_id` (`id`),
  KEY `ix_form_data_search` (`id`,`signbank`,`glos`),
  KEY `idx_form_data_glosZichtbaar` (`glosZichtbaar`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- medicijnen: not present in database

